### PR TITLE
User Input Checking for Navigation

### PR DESCRIPTION
**Pull request by smitja21**
Making it so users can't break the game as easily

### CODE REVIEW

**Comment by smitja21** [comment]
Some of my do while's might be broken, I think they weren't working 100% correctly

**Comment by smitja21** [comment]
The do while in broom1 checking the response "yes" or "no" if the math papers were marked is a bit jank and could be improved, but it works

**Comment by marojm1** [comment]
The fight() needs a do while that prevents the int option from breaking from an invalid option otherwise the other do whiles  seem to be working just fine.

**Comment by smitja21** [comment]
> The fight() needs a do while that prevents the int option from breaking from an invalid option otherwise the other do whiles seem to be working just fine.

Hopefully this has or will be resolved in the fight code improvements, the code has been changed a lot since I created the branch

**Pull request merged**
