### PR TITLE
Adding sound

### PR DESCRIPTION
**Pull request by marojm1**
Adding sound to :
Lose method and  Intro ascii

### CODE REVIEW

**Comment by marojm1** [comment]
I have removed the LaughBeep()

**Comment by smitja21** [comment]
I'll play test it

**Comment by smitja21** [comment]
I think it would be cool if the death sound was longer like you have flat lined

**Comment by marojm1** [comment]
Yeah I will  do that now .Thank you for the feedback

**Comment by smitja21** [comment]
Thank you very much for implemented the change, sounds good! I'll now merge the pull request into main

**Pull request merged**
