### PR TITLE
Doing more bug fixes, the usual

### PR DESCRIPTION
**Pull request by ZandarB**

### CODE REVIEW

**Comment by SaskiaBLittle** [comment]
It looks good and I will resolve comments now / add in any spaces needed

**Comment by smitja21** [comment]
I had a quite look over too, looks good. Thank you!

**Comment by ZandarB** [comment]
> It looks good and I will resolve comments now / add in any spaces needed

In the words of Elvis "Thank you, thank you very much"

**Comment by SaskiaBLittle** [comment]
Alrighty, I have commited all of the error fixes, it lookd fabulouse

**Pull request merged**
